- name: MS Java
  hosts: server
  become_user: "{{su_user}}"
  gather_facts: no
  #serial: 1

  tasks:

################### PRE-INSTALL ###########################

    - name: Create Backup/Release directories
      file: path="{{item}}/{{change_no}}/{{bld_no}}" state=directory mode=0755
      with_items:
        - "{{release_path}}"
        - "{{backup_path}}"
      tags: Pre_Install

    - name: Backup JDK8 with build number
      archive: path="{{old_java8_home}}" dest="{{backup_path}}/{{change_no}}/{{bld_no}}/{{old_8vrsn}}.tgz"
      tags: Pre_Install
      when: java8_home is defined and isJava8 == "YES"

    - name: Backup Java 11 with build number
      archive: path="{{old_java11_home}}" dest="{{backup_path}}/{{change_no}}/{{bld_no}}/{{old_11vrsn}}.tgz"
      tags: Pre_Install
      when: java11_home is defined and isJava11 == "YES"

    - name: Backup Java 17 with build number
      archive: path="{{old_java17_home}}" dest="{{backup_path}}/{{change_no}}/{{bld_no}}/{{old_17vrsn}}.tgz"
      tags: Pre_Install
      when: java17_home is defined and isJava17 == "YES"

    - name: Backup Open Java 17 with build number
      archive: path="{{old_openjava17_home}}" dest="{{backup_path}}/{{change_no}}/{{bld_no}}/{{old_open17vrsn}}.tgz"
      tags: Pre_Install
      when: openjava17_home is defined and isOpenJava17 == "YES"

    - name: Download java8 from Artifactory
      get_url:
        url: "{{ art8_url }}"
        dest: "{{ release_path }}/{{ change_no }}/{{ bld_no }}/{{ new_8vrsn }}.tgz"
        url_username: "{{ repouser }}"
        url_password: "{{ repopwd }}"
        use_proxy: yes
        timeout: 60
        mode: 0755
        validate_certs: false
      environment:
        http_proxy: http://{{proxy_url}}
        https_proxy: https://{{proxy_url}}
      when: java8_home is defined and isJava8 == "YES"
      tags: Pre_Install

    - name: Download java11 from Artifactory
      get_url:
        url: "{{ art11_url }}"
        dest: "{{ release_path }}/{{ change_no }}/{{ bld_no }}/{{ new_11vrsn }}.tgz"
        url_username: "{{ repouser }}"
        url_password: "{{ repopwd }}"
        use_proxy: yes
        timeout: 60
        mode: 0755
        validate_certs: false
      environment:
        http_proxy: http://{{proxy_url}}
        https_proxy: https://{{proxy_url}}
      when: java11_home is defined and isJava11 == "YES"
      tags: Pre_Install

    - name: Download java17 from Artifactory
      get_url:
        url: "{{ art17_url }}"
        dest: "{{ release_path }}/{{ change_no }}/{{ bld_no }}/{{ new_17vrsn }}.tgz"
        url_username: "{{ repouser }}"
        url_password: "{{ repopwd }}"
        use_proxy: yes
        timeout: 60
        mode: 0755
        validate_certs: false
      environment:
        http_proxy: http://{{proxy_url}}
        https_proxy: https://{{proxy_url}}
      when: java17_home is defined and isJava17 == "YES"
      tags: Pre_Install

    - name: Download Open java17 from Artifactory
      get_url:
        url: "{{ artOpen17_url }}"
        dest: "{{ release_path }}/{{ change_no }}/{{ bld_no }}/{{ new_open17vrsn }}.tgz"
        url_username: "{{ repouser }}"
        url_password: "{{ repopwd }}"
        use_proxy: yes
        timeout: 60
        mode: 0755
        validate_certs: false
      environment:
        http_proxy: http://{{proxy_url}}
        https_proxy: https://{{proxy_url}}
      when: openjava17_home is defined and isOpenJava17 == "YES"
      tags: Pre_Install

    - name: Download root cert from Artifactory
      get_url:
        url: "{{ root_url }}"
        dest: "{{ release_path }}/{{ change_no }}/{{ bld_no }}/root.cer"
        url_username: "{{ repouser }}"
        url_password: "{{ repopwd }}"
        use_proxy: yes
        mode: 0755
        validate_certs: false
      environment:
        http_proxy: http://{{proxy_url}}
        https_proxy: https://{{proxy_url}}
      tags: Pre_Install

    - name: Download inter cert from Artifactory
      get_url:
        url: "{{ inter_url }}"
        dest: "{{ release_path }}/{{ change_no }}/{{ bld_no }}/inter.cer"
        url_username: "{{ repouser }}"
        url_password: "{{ repopwd }}"
        use_proxy: yes
        mode: 0755
        validate_certs: false
      environment:
        http_proxy: http://{{proxy_url}}
        https_proxy: https://{{proxy_url}}
      tags: Pre_Install

################### UPGRADE #############################

#################### JDK 8 ##############################
    - name: Unzip the downloaded JDK8
      unarchive: src="{{release_path}}/{{change_no}}/{{bld_no}}/{{new_8vrsn}}.tgz"  dest="{{app_loc}}" mode=0755 remote_src=yes
      tags: Upgrade
      when: java8_home is defined and isJava8 == "YES"

    - name: Update the symbolic link for Java 8
      file: src={{new_java8_home}} dest="{{app_loc}}/{{sym8_link}}" state=link
      tags: Upgrade
      when: new_java8_home is defined and isJava8 == "YES"

    - name: Import certs in to cacerts for Java 8
      java_cert:
        cert_path: "{{release_path}}/{{change_no}}/{{bld_no}}/{{item.path}}"
        keystore_path: "{{ java8_home }}/jre/lib/security/cacerts"
        keystore_pass: changeit
        cert_alias: "{{item.alias}}"
        executable: "{{ java8_home }}/bin/keytool"
      with_items:
        - { path: "root.cer", alias: fnfis_root }
        - { path: "inter.cer", alias: fnfis_inter }
      tags: Upgrade
      when: java8_home is defined and isJava8 == "YES"

#################### JDK 11 ##############################

    - name: Unzip the downloaded JDK11
      unarchive: src="{{release_path}}/{{change_no}}/{{bld_no}}/{{new_11vrsn}}.tgz"  dest="{{app_loc}}" mode=0755 remote_src=yes
      tags: Upgrade
      when: java11_home is defined and isJava11 == "YES"

    - name: Update the symbolic link for Java 11
      file: src={{new_java11_home}} dest="{{app_loc}}/{{sym11_link}}" state=link
      tags: Upgrade
      when: new_java11_home is defined and isJava11 == "YES"

    - name: Import certs in to cacerts for Java 11
      java_cert:
        cert_path: "{{release_path}}/{{change_no}}/{{bld_no}}/{{item.path}}"
        keystore_path: "{{ java11_home }}/lib/security/cacerts"
        keystore_pass: changeit
        cert_alias: "{{item.alias}}"
        executable: "{{ java11_home }}/bin/keytool"
      with_items:
        - { path: "root.cer", alias: new_prod_root }
        - { path: "inter.cer", alias: new_prod_inter }
      tags: Upgrade
      when: java11_home is defined and isJava11 == "YES"

#################### JDK 17 ##############################

    - name: Unzip the downloaded JDK17
      unarchive: src="{{release_path}}/{{change_no}}/{{bld_no}}/{{new_17vrsn}}.tgz"  dest="{{app_loc}}" mode=0755 remote_src=yes
      tags: Upgrade
      when: java17_home is defined and isJava17 == "YES"

    - name: Update the symbolic link for Java 17
      file: src={{new_java17_home}} dest="{{app_loc}}/{{sym17_link}}" state=link
      tags: Upgrade
      when: new_java17_home is defined and isJava17 == "YES"

    - name: Import certs in to cacerts for Java 17
      java_cert:
        cert_path: "{{release_path}}/{{change_no}}/{{bld_no}}/{{item.path}}"
        keystore_path: "{{ java17_home }}/lib/security/cacerts"
        keystore_pass: changeit
        cert_alias: "{{item.alias}}"
        executable: "{{ java17_home }}/bin/keytool"
      with_items:
        - { path: "root.cer", alias: new_prod_root }
        - { path: "inter.cer", alias: new_prod_inter }
      tags: Upgrade
      when: java17_home is defined and isJava17 == "YES"

#################### OpenJDK 17 ##############################

    - name: Unzip the downloaded Open JDK17
      unarchive: src="{{release_path}}/{{change_no}}/{{bld_no}}/{{new_open17vrsn}}.tgz"  dest="{{app_loc}}" mode=0755 remote_src=yes
      tags: Upgrade
      when: openjava17_home is defined and isOpenJava17 == "YES"

    - name: Update the symbolic link for Open Java 17
      file: src={{new_openjava17_home}} dest="{{app_loc}}/{{symopen17_link}}" state=link
      tags: Upgrade
      when: new_openjava17_home is defined and isOpenJava17 == "YES"

## Cert update not requried for Open Java 17

#################### RESTART ##################################


    - name: Stop the Applications
      shell: "cd {{ item.path }} && sh {{ item.path }}/{{ stopScript }}"
      with_items: "{{ app_det }}"
      tags: Restart
      ignore_errors: true
      when: app_det is defined

    - name: Start the applications
      shell: "cd {{ item.path }} && nohup {{ item.path }}/{{ startScript }} &"
      args:
        chdir : "{{item.path}}"
      #register: startOutput
      tags: Restart
      with_items: "{{ app_det }}"
      ignore_errors: true
      when: app_det is defined

    - name: Check for started message
      shell: "grep '{{ item.upMsg }}' {{ item.path }}/serverstart.log"
      register: startSuccess
      until: startSuccess.stdout.find('JVM running') != -1
      delay: 5
      retries: 5
      tags: Restart
      with_items: "{{ app_det }}"
      ignore_errors: true
      when: app_det is defined

    - name: Failed Applications
      debug: msg="Failed - {{item.item.name}}"
      loop: "{{startSuccess.results}}"
      loop_control:
          label: ""
      tags: Restart
      ignore_errors: true
      when:
        - app_det is defined
        - "{{item.rc}} != 0"

################# Removing Old Java Folders ######################

    - name: Remove Java 8
      shell: "rm -rf {{old_java8_home}}"
      when: java8_home is defined and isJava8 == "YES"
      ignore_errors: true
      tags: Upgrade

    - name: Remove Java 11
      shell: "rm -rf {{old_java11_home}}"
      when: java11_home is defined and isJava11 == "YES"
      ignore_errors: true
      tags: Upgrade

    - name: Remove Java 17
      shell: "rm -rf {{old_java17_home}}"
      when: java17_home is defined and isJava17 == "YES"
      ignore_errors: true
      tags: Upgrade

    - name: Remove Open Java 17
      shell: "rm -rf {{old_openjava17_home}}"
      when: openjava17_home is defined and isOpenJava17 == "YES"
      ignore_errors: true
      tags: Upgrade
