//Tomcat_Upgrade
pipeline {

  agent {
    node {
      label "py27-ansible2-9-ora12c"
    }
  } // For Higher
  //agent { node { label "ansible" } } // For Scrum

  parameters {
    string defaultValue: '8.5.88', description: 'Enter the deploying Tomcat version', name: 'tmct_version', trim: true
    choice choices: ['SELECT', 'UAT', 'PROD'], description: 'Choose the environment', name: 'Environment'
    string defaultValue: '', description: 'Enter the Tomcat Download URL', name: 'tmct_url', trim: true
    string defaultValue: '', description: 'Enter the Change Number', name: 'ChangeNumber', trim: true
    string defaultValue: '', description: 'Enter if pre_install is done already, else ignore.', name: 'PreBuildNumber', trim: true
    choice choices: ['SELECT', 'yes', 'no'], description: 'Restart required ?', name: 'Restart'
  }

  environment {

    uat_servers = 'LRK4RSGDIPPAP01.prod.local,LRK4RSGDIPPAP02.prod.local'

    prod_servers = 'LRK1RSGDIPPAP01.prod.local,LRK1RSGDIPPAP02.prod.local'

  }

  stages {

    stage("Definition") {
      steps {
        script {

          release_path = "/data/SCMSupport/Releases"
          backup_path = "/data/SCMSupport/Backup"

          if (env.Environment == "UAT") {
            UAT_SERVERS = uat_servers.tokenize(',')
            ServerGroup = UAT_SERVERS
            slct_inv = "uat.ini"
            superuser = "tomcat"
            zone = "uat"
            creds_id1 = "tomcat_uat"
            proxy_url = "proxy.prod.local:8080"
          } else if (env.Environment == "PROD") {
            PROD_SERVERS = prod_servers.tokenize(',')
            ServerGroup = PROD_SERVERS
            slct_inv = "prod.ini"
            superuser = "tomcat"
            zone = "prod"
            creds_id1 = "tomcat_prod"
            proxy_url = "proxy.prod.local:8080"
          }
        }
      }
    }

    stage("Pre-Install") {
      steps {
        script {
          withCredentials([sshUserPrivateKey(credentialsId: "${creds_id1}", keyFileVariable: 'ssh_key')]) {
            if ("${ChangeNumber}" == "") {
              error("Change number is empty. Exiting")
            }
            echo "INFO: Downloading Tomcat"
            if (env.Environment == "UAT" || env.Environment == "PROD") {
              sh "export http_proxy=$proxy_url && export https_proxy=$proxy_url && wget -q ${tmct_url} -O ${tmct_version}.tgz --no-check-certificate"
            }
            for (server in ServerGroup) {
              echo "INFO: Transferring Artifacts"
              sh "ssh -i ${ssh_key} -q -o StrictHostKeyChecking=no ${superuser}@${server} mkdir -p ${release_path}/${ChangeNumber}/${BUILD_NUMBER}"
              sh "scp -i ${ssh_key} -q -o StrictHostKeyChecking=no ${tmct_version}.tgz ${superuser}@${server}:${release_path}/${ChangeNumber}/${BUILD_NUMBER}/"
              sh "ssh -i ${ssh_key} -q -o StrictHostKeyChecking=no ${superuser}@${server} ls ${release_path}/${ChangeNumber}/${BUILD_NUMBER}"
              echo "INFO: Artifacts transferred in ${server}"
            }
          }
        }
      }
    }

    stage("Upgrade") {
      steps {
        script {
          echo "INFO: Executing playbook."
          if ("${PreBuildNumber}" == "") {
            PreBuildNumber = "${BUILD_NUMBER}"
          }
          echo "${PreBuildNumber}"
          ansiblePlaybook(
            playbook: "TomcatUpgrade/ClientVue/playbook.yml",
            inventory: "TomcatUpgrade/ClientVue/higher/$slct_inv",
            credentialsId: "${creds_id1}",
            //extras: "-v",
            extraVars: [
              zone: "${zone}",
              tmct_vrsn: "${tmct_version}",
              pre_bld_no: "${PreBuildNumber}",
              bld_no: "${BUILD_NUMBER}",
              change_no: "${ChangeNumber}",
              restart: env.Restart
            ]
          )
        }
      }
    }
  }
}
