---
- hosts: "{{zone}}"
  become_user: "{{su_user}}"
  gather_facts: yes
  serial: "{{ serial_no }}"

  tasks:
    - name: Set backup path
      set_fact: backup_full_path="{{backup_path}}/{{change_no}}/{{ lookup('env','BUILD_NUMBER') }}"
      tags: backup, update, rollback

    - name: Set release path
      set_fact: release_full_path="{{release_path}}/{{change_no}}/{{build_no}}"
      tags: backup, update, rollback

    - name: Set Rollback path
      set_fact: rollback_path="{{backup_path}}/{{change_no}}/{{build_no}}"
      tags: rollback

    - name: Create directories
      file: path="{{item}}" state=directory mode=0755
      with_items:
        - "{{backup_full_path}}"
        - "{{release_full_path}}"
      tags: backup, update, rollback

    - name: Backup existing httpd folder excluding logs
      shell: cd {{web_loc}} ; tar --exclude="*logs*" -czvf {{backup_full_path}}/{{web_folder}}.tgz {{web_folder}}
      tags: backup, update, rollback

    - name: Create temp dir for folders to retain
      file: path="{{backup_full_path}}/retain_files/" state=directory mode=0755
      tags: update

    - name: Stop the services in DEV/QC/PROD/DR
      shell: "cd {{item}} && ./stop"
      with_items:
        - "{{csec_5000}}"
        - "{{csec_6000}}"
        #- "{{csec_8443}}"
      when: zone|lower == "dev" or zone|lower == "qc" or zone|lower == "prod" or zone|lower == "dr"
      register: stopweb_output
      until: stopweb_output.stdout.find("processes are already stopped") != -1
      tags: update, rollback
      ignore_errors: yes

    - name: Stop the services in UAT
      shell: "cd {{item}} && ./stop"
      register: stopweb_output
      with_items:
        - "{{csec_5000}}"
        - "{{csec_6000}}"
        - "{{csec_7000}}"
        - "{{csec_8443}}"
      when: zone|lower == "uat"
      until: stopweb_output.stdout.find("processes are already stopped") != -1
      delay: 5
      retries: 4
      ignore_errors: yes
      tags: update, rollback

    - name: Move folders to retain in Dev/QC/Prod/DR
      shell: "mv {{item}} {{backup_full_path}}/retain_files/"
      with_items:
        - "{{path_5000}}"
        - "{{path_6000}}"
        #- "{{path_8443}}"
        - "{{keys_path}}"
        - "{{urimaps_path}}"
      when: zone|lower == "dev" or zone|lower == "qc" or zone|lower == "prod" or zone|lower == "dr"
      tags: update

    - name: Move folders to retain in UAT
      shell: "mv {{item}} {{backup_full_path}}/retain_files/"
      with_items:
        - "{{path_5000}}"
        - "{{path_6000}}"
        - "{{path_7000}}"
        - "{{path_8443}}"
        - "{{keys_path}}"
        - "{{urimaps_path}}"
      when: zone|lower == "uat"
      tags: update

    - name: Rename the existing folder
      shell: mv {{web_loc}}/{{web_folder}} {{web_loc}}/{{web_folder}}_renamed
      tags: update, rollback

    - name: Unzip the downloaded JBCS package
      unarchive:
        src: "{{release_full_path}}/jbcs_{{new_jbcs_vrsn}}.zip"
        dest: "{{web_loc}}"
        mode: 0755
        remote_src: yes
      tags: update

    - name: Move back the retained files
      shell: "mv {{backup_full_path}}/retain_files/* {{web_loc}}/{{web_folder}}/httpd/."
      tags: update

    - name: Comment AJP module in 00-proxy.conf
      shell: "sed -i '/ajp/ s/LoadModule/#LoadModule/g' {{web_loc}}/{{web_folder}}/httpd/conf.modules.d/00-proxy.conf"
      tags: update

    - name: Untar from backup
      shell: "cd {{web_loc}} ; tar xf {{rollback_path}}/{{web_folder}}.tgz"
      tags: rollback

    - name: Replace logs folders to respective path
      shell: "mv {{web_loc}}/{{web_folder}}_renamed/httpd/{{item}}/logs {{web_loc}}/{{web_folder}}/httpd/{{item}}/."
      with_items:
        - 5000
        - 6000
      # - 8443
      when: zone|lower == "dev" or zone|lower == "qc" or zone|lower == "prod" or zone|lower == "dr"
      tags: rollback

    - name: Replace logs folders to respective path
      shell: "mv {{web_loc}}/{{web_folder}}_renamed/httpd/{{item}}/logs {{web_loc}}/{{web_folder}}/httpd/{{item}}/."
      with_items:
        - 5000
        - 6000
        - 7000
        - 8443
      when: zone|lower == "uat"
      tags: rollback

    - name: Update symbolic link
      shell: "cd {{web_loc}} ; rm {{sym_link}} ; ln -s {{web_folder}} {{sym_link}}"
      tags: update, rollback

    - name: Move 01-md.conf to backup
      shell: "mv {{web_loc}}/{{sym_link}}/httpd/conf.modules.d/01-md.conf {{backup_full_path}}/."
      tags: update, rollback

    - name: Take backup of 00-base.conf
      shell: "cp {{web_loc}}/{{sym_link}}/httpd/conf.modules.d/00-base.conf {{backup_full_path}}/."
      tags: update, rollback

    - name: Edit DefaultRuntimeDir of 00-base.conf
      lineinfile:
        path: "{{web_loc}}/{{sym_link}}/httpd/conf.modules.d/00-base.conf"
        regexp: "^DefaultRuntimeDir"
        line: "DefaultRuntimeDir /appl/Redhat/JBCS/httpd/run"
      tags: update, rollback

    - name: Remove the old httpd folder
      shell: "rm -rf {{web_loc}}/{{web_folder}}_renamed"
      tags: update, rollback

    - name: Start the services - Dev/QC/Prod/DR
      shell: "cd {{item}} && ./start"
      with_items:
        - "{{csec_5000}}"
        - "{{csec_6000}}"
      # - "{{csec_8443}}"
      when: zone|lower == "dev" or zone|lower == "qc" or zone|lower == "prod" or zone|lower == "dr"
      tags: update, rollback
      ignore_errors: yes

    - name: Start the services - UAT
      shell: "cd {{item}} && ./start"
      with_items:
        - "{{csec_5000}}"
        - "{{csec_6000}}"
        - "{{csec_7000}}"
        - "{{csec_8443}}"
      when: zone|lower == "uat"
      register: webstart_output
      ignore_errors: yes
      tags: update, rollback

    - name: Debug webstart_output
      debug: var=webstart_output.stdout
      tags: update, rollback
